# Generated by Django 5.0.1 on 2024-02-01 13:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, unique=True)),
                ('image', models.ImageField(blank=True, default='default/no_image.jpg', null=True, upload_to='blog/admin_images')),
                ('description', models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(20)])),
            ],
        ),
        migrations.CreateModel(
            name='CarPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=150)),
                ('car_model', models.CharField(max_length=150)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('excerpt', models.CharField(blank=True, default='Немає короткого опису', max_length=200)),
                ('image', models.ImageField(default='default/no_image.jpg', upload_to='blog/user_images')),
                ('slug', models.SlugField(unique=True)),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category')),
            ],
        ),
    ]
