# Generated by Django 5.0.1 on 2024-02-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_carpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpost',
            name='image',
            field=models.ImageField(default='default/no_image.jpg', upload_to='blog/user_images'),
        ),
    ]
